# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  issue_comment:
    types: [created]

name: Commands

jobs:
  document:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/document') }}
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up for RProtoBuf
        run: sudo apt-get update -y && sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: pr-document

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Config git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Check if there are any changes
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet -- NAMESPACE man/; then
            echo "has-changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "has-changed=true" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Commit the changes
        if: ${{ steps.check-changes.outputs.has-changed == 'true' }}
        run: |
          git add man/\* NAMESPACE
          git commit -m '[GHA] Document package'

      # Commit changes or a placeholder commit if no changes
      - name: Commit no changes
        if: ${{ steps.check-changes.outputs.has-changed == 'false' }}
        run: |
          git commit --allow-empty -m '[GHA] Package already documented'

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  style:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/style') }}
    name: style
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up for RProtoBuf
        run: sudo apt-get update -y && sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev

      - name: Install dependencies
        run: install.packages("styler")
        shell: Rscript {0}

      - name: Style
        run: styler::style_pkg(transformers = styler::tidyverse_style(indent_by = 4))
        shell: Rscript {0}

      - name: Config git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Check if there are any changes
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet -- '*.R'; then
            echo "has-changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "has-changed=true" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Commit the changes
        if: ${{ steps.check-changes.outputs.has-changed == 'true' }}
        run: |
          git add \*.R
          git commit -m '[GHA] Style package'

      # Commit changes or a placeholder commit if no changes
      - name: Commit no changes
        if: ${{ steps.check-changes.outputs.has-changed == 'false' }}
        run: |
          git commit --allow-empty -m '[GHA] Package already styled'

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
